/**
 * Interfaz desde la que se cambian los atributos de un usuario
 */
package InterfazGrafica.registrado;

import ciclodeinstruccion.Usuarios.Registrado;
import BaseDeDatos.ConsultasBD;

public class AtributosRegistrado extends javax.swing.JDialog {

    /**
     * Creates new form AtributosRegistrado
     */
    private Registrado registrado;
    private final int LIMITE_HABILIDAD=10;
    private InicioRegistrado ir;
    public AtributosRegistrado(java.awt.Frame parent, boolean modal, Registrado r, InicioRegistrado ir) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();  
        this.setLocationRelativeTo(null);
        this.registrado=r;
        this.ir=ir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menosInteligencia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        puntosDeNivel = new javax.swing.JLabel();
        vitalidad = new javax.swing.JLabel();
        fuerza = new javax.swing.JLabel();
        especial = new javax.swing.JLabel();
        inteligencia = new javax.swing.JLabel();
        masInteligencia = new javax.swing.JButton();
        masEspecial = new javax.swing.JButton();
        masFuerza = new javax.swing.JButton();
        masVitalidad = new javax.swing.JButton();
        menosVitalidad = new javax.swing.JButton();
        menosFuerza = new javax.swing.JButton();
        menosEspecial = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel1.setMaximumSize(new java.awt.Dimension(630, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 620));
        jPanel1.setLayout(null);

        menosInteligencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png"))); // NOI18N
        menosInteligencia.setBorderPainted(false);
        menosInteligencia.setContentAreaFilled(false);
        menosInteligencia.setFocusPainted(false);
        menosInteligencia.setMaximumSize(new java.awt.Dimension(80, 65));
        menosInteligencia.setMinimumSize(new java.awt.Dimension(80, 65));
        menosInteligencia.setPreferredSize(new java.awt.Dimension(80, 65));
        menosInteligencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menosInteligenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menosInteligenciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menosInteligenciaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosInteligenciaMouseReleased(evt);
            }
        });
        menosInteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosInteligenciaActionPerformed(evt);
            }
        });
        jPanel1.add(menosInteligencia);
        menosInteligencia.setBounds(60, 420, 80, 65);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Inteligencia");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 430, 120, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Especial");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 330, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Fuerza");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 230, 120, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Vitalidad");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 130, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 51));
        jLabel9.setText("Puntos de nivel disponibles:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 30, 333, 40);

        puntosDeNivel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        puntosDeNivel.setForeground(new java.awt.Color(255, 102, 51));
        puntosDeNivel.setText("Puntos");
        jPanel1.add(puntosDeNivel);
        puntosDeNivel.setBounds(450, 30, 83, 40);

        vitalidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vitalidad.setForeground(new java.awt.Color(255, 102, 51));
        vitalidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vitalidad.setText("Vitalidad");
        jPanel1.add(vitalidad);
        vitalidad.setBounds(350, 130, 120, 40);

        fuerza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fuerza.setForeground(new java.awt.Color(255, 102, 51));
        fuerza.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fuerza.setText("Fuerza");
        jPanel1.add(fuerza);
        fuerza.setBounds(350, 230, 120, 40);

        especial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        especial.setForeground(new java.awt.Color(255, 102, 51));
        especial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        especial.setText("Especial");
        jPanel1.add(especial);
        especial.setBounds(350, 330, 120, 40);

        inteligencia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inteligencia.setForeground(new java.awt.Color(255, 102, 51));
        inteligencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inteligencia.setText("Inteligencia");
        jPanel1.add(inteligencia);
        inteligencia.setBounds(350, 430, 120, 40);

        masInteligencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png"))); // NOI18N
        masInteligencia.setBorderPainted(false);
        masInteligencia.setContentAreaFilled(false);
        masInteligencia.setFocusPainted(false);
        masInteligencia.setMaximumSize(new java.awt.Dimension(80, 65));
        masInteligencia.setMinimumSize(new java.awt.Dimension(80, 65));
        masInteligencia.setPreferredSize(new java.awt.Dimension(80, 65));
        masInteligencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masInteligenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masInteligenciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masInteligenciaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masInteligenciaMouseReleased(evt);
            }
        });
        jPanel1.add(masInteligencia);
        masInteligencia.setBounds(490, 420, 80, 65);

        masEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png"))); // NOI18N
        masEspecial.setToolTipText("");
        masEspecial.setBorderPainted(false);
        masEspecial.setContentAreaFilled(false);
        masEspecial.setFocusPainted(false);
        masEspecial.setMaximumSize(new java.awt.Dimension(80, 65));
        masEspecial.setMinimumSize(new java.awt.Dimension(80, 65));
        masEspecial.setPreferredSize(new java.awt.Dimension(80, 65));
        masEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masEspecialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masEspecialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masEspecialMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masEspecialMouseReleased(evt);
            }
        });
        jPanel1.add(masEspecial);
        masEspecial.setBounds(490, 320, 80, 65);

        masFuerza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png"))); // NOI18N
        masFuerza.setBorderPainted(false);
        masFuerza.setContentAreaFilled(false);
        masFuerza.setFocusPainted(false);
        masFuerza.setMaximumSize(new java.awt.Dimension(80, 65));
        masFuerza.setMinimumSize(new java.awt.Dimension(80, 65));
        masFuerza.setPreferredSize(new java.awt.Dimension(80, 65));
        masFuerza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masFuerzaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masFuerzaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masFuerzaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masFuerzaMouseReleased(evt);
            }
        });
        jPanel1.add(masFuerza);
        masFuerza.setBounds(490, 220, 80, 65);

        masVitalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png"))); // NOI18N
        masVitalidad.setBorderPainted(false);
        masVitalidad.setContentAreaFilled(false);
        masVitalidad.setFocusPainted(false);
        masVitalidad.setMaximumSize(new java.awt.Dimension(80, 65));
        masVitalidad.setMinimumSize(new java.awt.Dimension(80, 65));
        masVitalidad.setPreferredSize(new java.awt.Dimension(80, 65));
        masVitalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masVitalidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masVitalidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masVitalidadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masVitalidadMouseReleased(evt);
            }
        });
        jPanel1.add(masVitalidad);
        masVitalidad.setBounds(490, 120, 80, 65);

        menosVitalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png"))); // NOI18N
        menosVitalidad.setBorder(null);
        menosVitalidad.setBorderPainted(false);
        menosVitalidad.setContentAreaFilled(false);
        menosVitalidad.setFocusPainted(false);
        menosVitalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menosVitalidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menosVitalidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menosVitalidadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosVitalidadMouseReleased(evt);
            }
        });
        menosVitalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosVitalidadActionPerformed(evt);
            }
        });
        jPanel1.add(menosVitalidad);
        menosVitalidad.setBounds(60, 120, 80, 65);

        menosFuerza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png"))); // NOI18N
        menosFuerza.setBorderPainted(false);
        menosFuerza.setContentAreaFilled(false);
        menosFuerza.setFocusPainted(false);
        menosFuerza.setMaximumSize(new java.awt.Dimension(80, 65));
        menosFuerza.setMinimumSize(new java.awt.Dimension(80, 65));
        menosFuerza.setPreferredSize(new java.awt.Dimension(80, 65));
        menosFuerza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menosFuerzaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menosFuerzaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menosFuerzaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosFuerzaMouseReleased(evt);
            }
        });
        jPanel1.add(menosFuerza);
        menosFuerza.setBounds(60, 220, 80, 65);

        menosEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png"))); // NOI18N
        menosEspecial.setBorderPainted(false);
        menosEspecial.setContentAreaFilled(false);
        menosEspecial.setFocusPainted(false);
        menosEspecial.setMaximumSize(new java.awt.Dimension(80, 65));
        menosEspecial.setMinimumSize(new java.awt.Dimension(80, 65));
        menosEspecial.setPreferredSize(new java.awt.Dimension(80, 65));
        menosEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menosEspecialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menosEspecialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menosEspecialMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosEspecialMouseReleased(evt);
            }
        });
        menosEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosEspecialActionPerformed(evt);
            }
        });
        jPanel1.add(menosEspecial);
        menosEspecial.setBounds(60, 320, 80, 65);

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/volver.png"))); // NOI18N
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setFocusPainted(false);
        volver.setMaximumSize(new java.awt.Dimension(260, 65));
        volver.setMinimumSize(new java.awt.Dimension(260, 65));
        volver.setPreferredSize(new java.awt.Dimension(260, 65));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                volverMouseReleased(evt);
            }
        });
        jPanel1.add(volver);
        volver.setBounds(180, 530, 260, 65);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(330, 40, 630, 620);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_normal.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel5.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel5.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masVitalidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVitalidadMouseEntered
        masVitalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/mas.png")));
    }//GEN-LAST:event_masVitalidadMouseEntered

    private void masFuerzaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masFuerzaMouseReleased
        if(masFuerza.isEnabled()){
            registrado.modificarFuerza();
            ConsultasBD.instancia().modificarRegistrado(registrado);
            //this.setVisible(false);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_masFuerzaMouseReleased

    private void masVitalidadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVitalidadMouseReleased
        if(masVitalidad.isEnabled()){
            registrado.modificarVitalidad();
            ConsultasBD.instancia().modificarRegistrado(registrado);
            //this.setVisible(false);
            this.mostrar();
            this.setVisible(true);    
        }
        
    }//GEN-LAST:event_masVitalidadMouseReleased

    private void masEspecialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMouseReleased
        if(masEspecial.isEnabled()){
            registrado.modificarEspecial();
            ConsultasBD.instancia().modificarRegistrado(registrado);
            //this.setVisible(false);
            this.mostrar();
            this.setVisible(true);    
        }
        
    }//GEN-LAST:event_masEspecialMouseReleased

    private void masInteligenciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masInteligenciaMouseReleased
        if(masInteligencia.isEnabled()){
            registrado.modificarInteligencia();
            ConsultasBD.instancia().modificarRegistrado(registrado);
            //this.setVisible(false);
            this.mostrar();
            this.setVisible(true);    
        }
        
    }//GEN-LAST:event_masInteligenciaMouseReleased

    private void menosVitalidadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVitalidadMouseReleased
        if(menosVitalidad.isEnabled()){
            registrado.disminuirVidalidad();
            ConsultasBD.instancia().modificarRegistrado(registrado);
            //this.setVisible(false);
            this.mostrar();
            this.setVisible(true);    
        }
        
    }//GEN-LAST:event_menosVitalidadMouseReleased

    private void menosFuerzaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosFuerzaMouseReleased
        if(menosFuerza.isEnabled()){
            registrado.disminuirFuerza();
            ConsultasBD.instancia().modificarRegistrado(registrado);
            //this.setVisible(false);
            this.mostrar();
            this.setVisible(true);    
        }
        
    }//GEN-LAST:event_menosFuerzaMouseReleased

    private void menosEspecialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMouseReleased
        if(menosEspecial.isEnabled()){
            registrado.disminuirEspecial();
            ConsultasBD.instancia().modificarRegistrado(registrado);
            //this.setVisible(false);
            this.mostrar();
            this.setVisible(true);    
        }
        
    }//GEN-LAST:event_menosEspecialMouseReleased

    private void menosInteligenciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosInteligenciaMouseReleased
        if(menosInteligencia.isEnabled()){
            registrado.disminuirInteligencia();
            ConsultasBD.instancia().modificarRegistrado(registrado);
            //this.setVisible(false);
            this.mostrar();
            this.setVisible(true);    
        }
        
    }//GEN-LAST:event_menosInteligenciaMouseReleased

    private void volverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseReleased
        ir.mostrar2();
        this.setVisible(false);
        ir.setVisible(true);
    }//GEN-LAST:event_volverMouseReleased

    private void menosVitalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosVitalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosVitalidadActionPerformed

    private void menosEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosEspecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosEspecialActionPerformed

    private void menosVitalidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVitalidadMousePressed
      menosVitalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/menos.png")));
    }//GEN-LAST:event_menosVitalidadMousePressed

    private void menosVitalidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVitalidadMouseEntered
      menosVitalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/menos.png")));
    }//GEN-LAST:event_menosVitalidadMouseEntered
    
    private void menosFuerzaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosFuerzaMouseEntered
       menosFuerza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/menos.png")));
    }//GEN-LAST:event_menosFuerzaMouseEntered

    private void menosEspecialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMousePressed
        menosEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/menos.png"))); 
    }//GEN-LAST:event_menosEspecialMousePressed

    private void menosEspecialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMouseEntered
        menosEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/menos.png"))); 
    }//GEN-LAST:event_menosEspecialMouseEntered

    private void menosInteligenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosInteligenciaMousePressed
        menosInteligencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/menos.png")));
    }//GEN-LAST:event_menosInteligenciaMousePressed

    private void menosInteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosInteligenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosInteligenciaActionPerformed

    private void menosInteligenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosInteligenciaMouseEntered
        menosInteligencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/menos.png")));
    }//GEN-LAST:event_menosInteligenciaMouseEntered

    private void masVitalidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVitalidadMousePressed
        masVitalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/mas.png")));
    }//GEN-LAST:event_masVitalidadMousePressed

    private void masFuerzaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masFuerzaMouseEntered
        masFuerza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/mas.png")));
    }//GEN-LAST:event_masFuerzaMouseEntered

    private void masFuerzaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masFuerzaMousePressed
        masFuerza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/mas.png")));
    }//GEN-LAST:event_masFuerzaMousePressed

    private void masEspecialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMouseEntered
        masEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/mas.png")));
    }//GEN-LAST:event_masEspecialMouseEntered

    private void masEspecialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMousePressed
        masEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/mas.png")));
    }//GEN-LAST:event_masEspecialMousePressed

    private void masInteligenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masInteligenciaMouseEntered
        masInteligencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/mas.png")));
    }//GEN-LAST:event_masInteligenciaMouseEntered

    private void masInteligenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masInteligenciaMousePressed
        masInteligencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/mas.png")));
    }//GEN-LAST:event_masInteligenciaMousePressed

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/volver.png")));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMousePressed
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/volver.png")));
    }//GEN-LAST:event_volverMousePressed

    private void menosVitalidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVitalidadMouseExited
       menosVitalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png")));
    }//GEN-LAST:event_menosVitalidadMouseExited

    private void menosFuerzaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosFuerzaMouseExited
        menosFuerza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png")));
    }//GEN-LAST:event_menosFuerzaMouseExited

    private void menosEspecialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMouseExited
        menosEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png")));
    }//GEN-LAST:event_menosEspecialMouseExited

    private void menosInteligenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosInteligenciaMouseExited
        menosInteligencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png")));
    }//GEN-LAST:event_menosInteligenciaMouseExited

    private void masVitalidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVitalidadMouseExited
        masVitalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png")));
    }//GEN-LAST:event_masVitalidadMouseExited

    private void masFuerzaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masFuerzaMouseExited
        masFuerza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png")));
    }//GEN-LAST:event_masFuerzaMouseExited

    private void masEspecialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMouseExited
        masEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png")));
    }//GEN-LAST:event_masEspecialMouseExited

    private void masInteligenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masInteligenciaMouseExited
        masInteligencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png")));
    }//GEN-LAST:event_masInteligenciaMouseExited

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/volver.png")));
    }//GEN-LAST:event_volverMouseExited

    private void menosFuerzaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosFuerzaMousePressed
        menosFuerza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/menos.png")));
    }//GEN-LAST:event_menosFuerzaMousePressed
    /**
     * Activa o desactiva los botones +/- en función de si hay puntos desiponibles
     * o de si se ha alcanzado el límite máximo(10) o mínimo (0) de los atributos
     */
    public void mostrar(){
        puntosDeNivel.setText(Integer.toString(registrado.getPuntosNivel()));
        vitalidad.setText(Integer.toString(registrado.getVitalidad()));
        fuerza.setText(Integer.toString(registrado.getFuerza()));
        especial.setText(Integer.toString(registrado.getEspecial()));
        inteligencia.setText(Integer.toString(registrado.getInteligencia()));
        this.repaint();
        if(registrado.getPuntosNivel()<=0){
            masEspecial.setEnabled(false);
            masVitalidad.setEnabled(false);
            masFuerza.setEnabled(false);
            masInteligencia.setEnabled(false);
        } 
        else{
            if(registrado.getVitalidad()>=LIMITE_HABILIDAD){
                masVitalidad.setEnabled(false);
            } else {
                masVitalidad.setEnabled(true);
            }
            if(registrado.getFuerza()>=LIMITE_HABILIDAD){
                masFuerza.setEnabled(false);
            } else {
                masFuerza.setEnabled(true);
            }
            if(registrado.getEspecial()>=LIMITE_HABILIDAD){
                masEspecial.setEnabled(false);
            } else {
                masEspecial.setEnabled(true);
            }
            if(registrado.getInteligencia()>=LIMITE_HABILIDAD){
                masInteligencia.setEnabled(false);
            } else {
                masInteligencia.setEnabled(true);
            }
        }
        
        if(registrado.getVitalidad()<=0){
            menosVitalidad.setEnabled(false);
        } else {
            menosVitalidad.setEnabled(true);
        }
        

        if(registrado.getFuerza()<=0){
            menosFuerza.setEnabled(false);
        } else {
            menosFuerza.setEnabled(true);
        }
        

        if(registrado.getEspecial()<=0){
            menosEspecial.setEnabled(false);
        } else {
            menosEspecial.setEnabled(true);
        }
        

        if(registrado.getInteligencia()<=0){
            menosInteligencia.setEnabled(false);
        } else {
            menosInteligencia.setEnabled(true);
        }
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtributosRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtributosRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtributosRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtributosRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AtributosRegistrado dialog = new AtributosRegistrado(new javax.swing.JFrame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel especial;
    private javax.swing.JLabel fuerza;
    private javax.swing.JLabel inteligencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton masEspecial;
    private javax.swing.JButton masFuerza;
    private javax.swing.JButton masInteligencia;
    private javax.swing.JButton masVitalidad;
    private javax.swing.JButton menosEspecial;
    private javax.swing.JButton menosFuerza;
    private javax.swing.JButton menosInteligencia;
    private javax.swing.JButton menosVitalidad;
    private javax.swing.JLabel puntosDeNivel;
    private javax.swing.JLabel vitalidad;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
