/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica.registrado;

import InterfazGrafica.registrado.MisPersonajes;
import MiPersonaje.*;
import ciclodeinstruccion.Usuarios.Registrado;
import BaseDeDatos.consultasBD;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Rubén
 */
public class AtributosMiPersonaje extends javax.swing.JDialog {

    /**
     * Creates new form AtributosMiPersonaje
     */
    MiPersonaje miPersonaje;
    Registrado registrado;
    private final int LIMITE_ATRIBUTO=10;
    MisPersonajes mp;
    public AtributosMiPersonaje(java.awt.Frame parent, boolean modal, MiPersonaje mp, Registrado r, MisPersonajes misp) {
        super(parent, modal);
        initComponents();
        this.miPersonaje=mp;
        this.registrado=r;
        this.mp=misp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPersonaje = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelEspecialP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menosVida = new javax.swing.JButton();
        menosDaño = new javax.swing.JButton();
        menosEspecial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelEspecial = new javax.swing.JLabel();
        nombreP = new javax.swing.JLabel();
        nivel = new javax.swing.JLabel();
        experienciaP = new javax.swing.JLabel();
        vidaP = new javax.swing.JLabel();
        especialP = new javax.swing.JLabel();
        dañoP = new javax.swing.JLabel();
        puntosNivel = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        daño = new javax.swing.JLabel();
        especial = new javax.swing.JLabel();
        masVida = new javax.swing.JButton();
        masDaño = new javax.swing.JButton();
        masEspecial = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        imagenPersonaje.setMaximumSize(new java.awt.Dimension(300, 450));
        imagenPersonaje.setMinimumSize(new java.awt.Dimension(300, 450));
        imagenPersonaje.setPreferredSize(new java.awt.Dimension(300, 450));
        getContentPane().add(imagenPersonaje);
        imagenPersonaje.setBounds(169, 92, 300, 450);

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/volver.png"))); // NOI18N
        volver.setBorder(null);
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setFocusPainted(false);
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                volverMouseReleased(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver);
        volver.setBounds(190, 590, 260, 65);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 20, 96, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Nivel");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 70, 61, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("Experiencia");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 120, 139, 60);

        labelEspecialP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEspecialP.setForeground(new java.awt.Color(255, 102, 51));
        labelEspecialP.setText("Especial");
        jPanel1.add(labelEspecialP);
        labelEspecialP.setBounds(130, 270, 140, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("Daño");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 220, 62, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("Vida");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 170, 52, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Puntos de nivel");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 320, 183, 60);

        menosVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png"))); // NOI18N
        menosVida.setBorder(null);
        menosVida.setBorderPainted(false);
        menosVida.setContentAreaFilled(false);
        menosVida.setFocusPainted(false);
        menosVida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menosVidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menosVidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menosVidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosVidaMouseReleased(evt);
            }
        });
        menosVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosVidaActionPerformed(evt);
            }
        });
        jPanel1.add(menosVida);
        menosVida.setBounds(30, 380, 80, 65);

        menosDaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png"))); // NOI18N
        menosDaño.setBorder(null);
        menosDaño.setBorderPainted(false);
        menosDaño.setContentAreaFilled(false);
        menosDaño.setFocusPainted(false);
        menosDaño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menosDañoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menosDañoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menosDañoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosDañoMouseReleased(evt);
            }
        });
        menosDaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosDañoActionPerformed(evt);
            }
        });
        jPanel1.add(menosDaño);
        menosDaño.setBounds(30, 460, 80, 65);

        menosEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png"))); // NOI18N
        menosEspecial.setBorder(null);
        menosEspecial.setBorderPainted(false);
        menosEspecial.setContentAreaFilled(false);
        menosEspecial.setFocusPainted(false);
        menosEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menosEspecialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menosEspecialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menosEspecialMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosEspecialMouseReleased(evt);
            }
        });
        jPanel1.add(menosEspecial);
        menosEspecial.setBounds(30, 540, 80, 65);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Bonus de vida");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 390, 166, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Bonus de daño");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 470, 175, 60);

        labelEspecial.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEspecial.setForeground(new java.awt.Color(255, 102, 51));
        labelEspecial.setText("Especial");
        jPanel1.add(labelEspecial);
        labelEspecial.setBounds(140, 550, 270, 60);

        nombreP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nombreP.setForeground(new java.awt.Color(255, 102, 51));
        nombreP.setText("mi nombre");
        jPanel1.add(nombreP);
        nombreP.setBounds(340, 20, 250, 60);

        nivel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nivel.setForeground(new java.awt.Color(255, 102, 51));
        nivel.setText("mi nivel");
        jPanel1.add(nivel);
        nivel.setBounds(340, 70, 94, 60);

        experienciaP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        experienciaP.setForeground(new java.awt.Color(255, 102, 51));
        experienciaP.setText("mi experiencia");
        jPanel1.add(experienciaP);
        experienciaP.setBounds(340, 120, 175, 60);

        vidaP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vidaP.setForeground(new java.awt.Color(255, 102, 51));
        vidaP.setText("mi vida");
        jPanel1.add(vidaP);
        vidaP.setBounds(340, 170, 87, 60);

        especialP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        especialP.setForeground(new java.awt.Color(255, 102, 51));
        especialP.setText("mi especial");
        jPanel1.add(especialP);
        especialP.setBounds(340, 270, 133, 60);

        dañoP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dañoP.setForeground(new java.awt.Color(255, 102, 51));
        dañoP.setText("mi daño");
        jPanel1.add(dañoP);
        dañoP.setBounds(340, 220, 96, 60);

        puntosNivel.setBackground(new java.awt.Color(0, 0, 0,0));
        puntosNivel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        puntosNivel.setForeground(new java.awt.Color(255, 102, 51));
        puntosNivel.setText("puntos nivel");
        jPanel1.add(puntosNivel);
        puntosNivel.setBounds(340, 320, 146, 60);

        vida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vida.setForeground(new java.awt.Color(255, 102, 51));
        vida.setText("miVida");
        jPanel1.add(vida);
        vida.setBounds(410, 390, 82, 60);

        daño.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        daño.setForeground(new java.awt.Color(255, 102, 51));
        daño.setText("miDaño");
        jPanel1.add(daño);
        daño.setBounds(410, 470, 92, 60);

        especial.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        especial.setForeground(new java.awt.Color(255, 102, 51));
        especial.setText("miEspecial");
        jPanel1.add(especial);
        especial.setBounds(410, 550, 127, 60);

        masVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png"))); // NOI18N
        masVida.setBorder(null);
        masVida.setBorderPainted(false);
        masVida.setContentAreaFilled(false);
        masVida.setFocusPainted(false);
        masVida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masVidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masVidaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masVidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masVidaMouseReleased(evt);
            }
        });
        jPanel1.add(masVida);
        masVida.setBounds(520, 380, 80, 65);

        masDaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png"))); // NOI18N
        masDaño.setBorder(null);
        masDaño.setBorderPainted(false);
        masDaño.setContentAreaFilled(false);
        masDaño.setFocusPainted(false);
        masDaño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masDañoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masDañoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masDañoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masDañoMouseReleased(evt);
            }
        });
        jPanel1.add(masDaño);
        masDaño.setBounds(520, 460, 80, 65);

        masEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png"))); // NOI18N
        masEspecial.setBorder(null);
        masEspecial.setBorderPainted(false);
        masEspecial.setContentAreaFilled(false);
        masEspecial.setFocusPainted(false);
        masEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masEspecialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masEspecialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                masEspecialMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masEspecialMouseReleased(evt);
            }
        });
        jPanel1.add(masEspecial);
        masEspecial.setBounds(520, 540, 80, 65);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 40, 630, 620);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_normal.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masVidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVidaMouseReleased
        if(masVida.isEnabled()){
            miPersonaje.aumentarBonusVida();
            consultasBD.instancia().modificarMiPersonaje(miPersonaje, registrado);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_masVidaMouseReleased

    private void masDañoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masDañoMouseReleased
        if(masDaño.isEnabled()){
            miPersonaje.aumentarBonusDaño();
            consultasBD.instancia().modificarMiPersonaje(miPersonaje, registrado);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_masDañoMouseReleased

    private void masEspecialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMouseReleased
        if(masEspecial.isEnabled()){
            if(miPersonaje instanceof MiTanque){
                MiTanque mt =(MiTanque) miPersonaje;
                mt.aumentarArmadura();
                consultasBD.instancia().modificarMiPersonaje(mt, registrado);
            }
            else if(miPersonaje instanceof MiAsesino){
                MiAsesino ma =(MiAsesino) miPersonaje;
                ma.aumentarEsquivar();
                consultasBD.instancia().modificarMiPersonaje(ma, registrado);
            }
            else if(miPersonaje instanceof MiFighter){
                MiFighter mf =(MiFighter) miPersonaje;
                mf.aumentarCritico();
                consultasBD.instancia().modificarMiPersonaje(mf, registrado);
            }
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_masEspecialMouseReleased

    private void menosVidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVidaMouseReleased
        if(menosVida.isEnabled()){
            miPersonaje.disminuirBonusVida();
            consultasBD.instancia().modificarMiPersonaje(miPersonaje, registrado);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_menosVidaMouseReleased

    private void menosDañoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosDañoMouseReleased
        if(menosDaño.isEnabled()){
            miPersonaje.disminuirBonusDaño();
            consultasBD.instancia().modificarMiPersonaje(miPersonaje, registrado);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_menosDañoMouseReleased

    private void menosEspecialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMouseReleased
        if(menosEspecial.isEnabled()){
            if(miPersonaje instanceof MiTanque){
                MiTanque mt =(MiTanque) miPersonaje;
                mt.disminuirArmadura();
                consultasBD.instancia().modificarMiPersonaje(mt, registrado);
            }
            else if(miPersonaje instanceof MiAsesino){
                MiAsesino ma =(MiAsesino) miPersonaje;
                ma.disminuirEsquivar();
                consultasBD.instancia().modificarMiPersonaje(ma, registrado);
            }
            else if(miPersonaje instanceof MiFighter){
                MiFighter mf =(MiFighter) miPersonaje;
                mf.disminuirCritico();
                consultasBD.instancia().modificarMiPersonaje(mf, registrado);
            }
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_menosEspecialMouseReleased

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    private void volverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseReleased
        this.setVisible(false);
        mp.mostrar();
        mp.setVisible(true);
    }//GEN-LAST:event_volverMouseReleased

    private void menosVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosVidaActionPerformed

    private void menosDañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosDañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosDañoActionPerformed

    private void masVidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVidaMousePressed
        masVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/mas.png")));
    }//GEN-LAST:event_masVidaMousePressed

    private void masVidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVidaMouseExited
        masVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png")));
    }//GEN-LAST:event_masVidaMouseExited

    private void masVidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVidaMouseEntered
        masVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/mas.png")));
    }//GEN-LAST:event_masVidaMouseEntered

    private void masDañoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masDañoMousePressed
        masDaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/mas.png")));
    }//GEN-LAST:event_masDañoMousePressed

    private void masDañoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masDañoMouseExited
        masDaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png")));
    }//GEN-LAST:event_masDañoMouseExited

    private void masDañoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masDañoMouseEntered
        masDaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/mas.png")));
    }//GEN-LAST:event_masDañoMouseEntered

    private void masEspecialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMousePressed
        masEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/mas.png")));
    }//GEN-LAST:event_masEspecialMousePressed

    private void masEspecialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMouseExited
        masEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/mas.png")));
    }//GEN-LAST:event_masEspecialMouseExited

    private void masEspecialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMouseEntered
        masEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/mas.png")));
    }//GEN-LAST:event_masEspecialMouseEntered

    private void menosVidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVidaMousePressed
        menosVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/menos.png")));
    }//GEN-LAST:event_menosVidaMousePressed

    private void menosVidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVidaMouseExited
        menosVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png")));
    }//GEN-LAST:event_menosVidaMouseExited

    private void menosVidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVidaMouseEntered
        menosVida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/menos.png")));
    }//GEN-LAST:event_menosVidaMouseEntered

    private void menosDañoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosDañoMousePressed
        menosDaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/menos.png")));
    }//GEN-LAST:event_menosDañoMousePressed

    private void menosDañoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosDañoMouseExited
        menosDaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png")));
    }//GEN-LAST:event_menosDañoMouseExited

    private void menosDañoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosDañoMouseEntered
        menosDaño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/menos.png")));
    }//GEN-LAST:event_menosDañoMouseEntered

    private void menosEspecialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMousePressed
        menosEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/menos.png")));
    }//GEN-LAST:event_menosEspecialMousePressed

    private void menosEspecialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMouseExited
        menosEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/menos.png")));
    }//GEN-LAST:event_menosEspecialMouseExited

    private void menosEspecialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMouseEntered
        menosEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/menos.png")));
    }//GEN-LAST:event_menosEspecialMouseEntered

    private void volverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMousePressed
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/volver.png")));
    }//GEN-LAST:event_volverMousePressed

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/volver.png")));
    }//GEN-LAST:event_volverMouseExited

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/volver.png")));
    }//GEN-LAST:event_volverMouseEntered
    public void mostrar(){
        vida.setText(Float.toString(miPersonaje.getBonusVida()));
        daño.setText(Float.toString(miPersonaje.getBonusDaño()));
        puntosNivel.setText(Integer.toString(miPersonaje.getPuntosNivel()));
        nombreP.setText(miPersonaje.getNombre());
        nivel.setText(Integer.toString(miPersonaje.getNivel()));
        experienciaP.setText(Integer.toString(miPersonaje.getExperiencia()));
        vidaP.setText(Float.toString(miPersonaje.getVidaBase()));
        dañoP.setText(Float.toString(miPersonaje.getDañoBase()));
        this.repaint();
        Image img=new ImageIcon(this.getClass().getResource("/Imagenes/Personajes/"+this.miPersonaje.getNombre()+".jpg")).getImage();
        imagenPersonaje.setIcon(new ImageIcon(img));
        float aEspecial=0;
        if(miPersonaje instanceof MiTanque){
            MiTanque mt=(MiTanque) miPersonaje;
            labelEspecial.setText("Bonus de armadura");
            especial.setText(Float.toString(mt.getBonusArmadura()));
            aEspecial=mt.getBonusArmadura();
            labelEspecialP.setText("Armadura");
            especialP.setText(Float.toString(mt.getPersonaje().getArmadura()));
        }
        else if(miPersonaje instanceof MiAsesino){
            MiAsesino ma=(MiAsesino) miPersonaje;
            labelEspecial.setText("Bonus de esquivar");
            especial.setText(Float.toString(ma.getBonusEsquivar()));
            aEspecial=ma.getBonusEsquivar();
            labelEspecialP.setText("Esquivar");
            especialP.setText(Float.toString(ma.getPersonaje().getEsquivar()));
        }
        else if(miPersonaje instanceof MiFighter){
            MiFighter mf=(MiFighter) miPersonaje;
            labelEspecial.setText("Bonus de crítico");
            especial.setText(Float.toString(mf.getBonusCritico()));
            aEspecial=mf.getBonusCritico();
            labelEspecialP.setText("Crítico");
            especialP.setText(Float.toString(mf.getPersonaje().getCritico()));
        }
        
        if(miPersonaje.getPuntosNivel()<=0){
            masDaño.setEnabled(false);
            masVida.setEnabled(false);
            masEspecial.setEnabled(false);
        }
        else{
            if(miPersonaje.getBonusVida()>=(10*LIMITE_ATRIBUTO)){//la vida aumenta en 10 cada vez que se sube un punto
                masVida.setEnabled(false);
            } else {
                masVida.setEnabled(true);
            }
            if (miPersonaje.getBonusDaño()>=(5*LIMITE_ATRIBUTO)){//el daño aumenta en 5 cada vez que se sube un punto
                masDaño.setEnabled(false);
            } else {
                masDaño.setEnabled(true);
            }
            if(aEspecial>=LIMITE_ATRIBUTO){//el especial aumenta en 1 cada vez que se sube un punto
                masEspecial.setEnabled(false);
            } else {
                masEspecial.setEnabled(true);
            }            
        }
        
        if(miPersonaje.getBonusVida()<=0){
            menosVida.setEnabled(false);
        } else {
            menosVida.setEnabled(true);
        }
        if(miPersonaje.getBonusDaño()<=0){
            menosDaño.setEnabled(false);
        } else {
            menosDaño.setEnabled(true);
        }
        if(aEspecial<=0){
            menosEspecial.setEnabled(false);
        } else {
            menosEspecial.setEnabled(true);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtributosMiPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtributosMiPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtributosMiPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtributosMiPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AtributosMiPersonaje dialog = new AtributosMiPersonaje(new javax.swing.JFrame(), true,null,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daño;
    private javax.swing.JLabel dañoP;
    private javax.swing.JLabel especial;
    private javax.swing.JLabel especialP;
    private javax.swing.JLabel experienciaP;
    private javax.swing.JLabel imagenPersonaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEspecial;
    private javax.swing.JLabel labelEspecialP;
    private javax.swing.JButton masDaño;
    private javax.swing.JButton masEspecial;
    private javax.swing.JButton masVida;
    private javax.swing.JButton menosDaño;
    private javax.swing.JButton menosEspecial;
    private javax.swing.JButton menosVida;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel nombreP;
    private javax.swing.JLabel puntosNivel;
    private javax.swing.JLabel vida;
    private javax.swing.JLabel vidaP;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
