/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica.registrado;

import InterfazGrafica.registrado.MisPersonajes;
import MiPersonaje.*;
import ciclodeinstruccion.Usuarios.Registrado;
import BaseDeDatos.consultasBD;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Rubén
 */
public class AtributosMiPersonaje extends javax.swing.JDialog {

    /**
     * Creates new form AtributosMiPersonaje
     */
    MiPersonaje miPersonaje;
    Registrado registrado;
    private final int LIMITE_ATRIBUTO=10;
    MisPersonajes mp;
    public AtributosMiPersonaje(java.awt.Frame parent, boolean modal, MiPersonaje mp, Registrado r, MisPersonajes misp) {
        super(parent, modal);
        initComponents();
        this.miPersonaje=mp;
        this.registrado=r;
        this.mp=misp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelEspecial = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        daño = new javax.swing.JLabel();
        especial = new javax.swing.JLabel();
        masVida = new javax.swing.JButton();
        masDaño = new javax.swing.JButton();
        masEspecial = new javax.swing.JButton();
        menosVida = new javax.swing.JButton();
        menosDaño = new javax.swing.JButton();
        menosEspecial = new javax.swing.JButton();
        puntosNivel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelEspecialP = new javax.swing.JLabel();
        nombreP = new javax.swing.JLabel();
        nivel = new javax.swing.JLabel();
        dañoP = new javax.swing.JLabel();
        vidaP = new javax.swing.JLabel();
        especialP = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        experienciaP = new javax.swing.JLabel();
        imagenPersonaje = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Bonus de vida");

        jLabel2.setText("Bonus de daño");

        labelEspecial.setText("Especial");

        jLabel4.setText("Puntos de nivel");

        vida.setText("miVida");

        daño.setText("miDaño");

        especial.setText("miEspecial");

        masVida.setText("+");
        masVida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masVidaMouseReleased(evt);
            }
        });

        masDaño.setText("+");
        masDaño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masDañoMouseReleased(evt);
            }
        });

        masEspecial.setText("+");
        masEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masEspecialMouseReleased(evt);
            }
        });

        menosVida.setText("-");
        menosVida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosVidaMouseReleased(evt);
            }
        });

        menosDaño.setText("-");
        menosDaño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosDañoMouseReleased(evt);
            }
        });

        menosEspecial.setText("-");
        menosEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menosEspecialMouseReleased(evt);
            }
        });

        puntosNivel.setText("puntos nivel");

        jLabel3.setText("Nombre");

        jLabel5.setText("Nivel");

        jLabel6.setText("Daño");

        jLabel7.setText("Vida");

        labelEspecialP.setText("Especial");

        nombreP.setText("mi nombre");

        nivel.setText("mi nivel");

        dañoP.setText("mi daño");

        vidaP.setText("mi vida");

        especialP.setText("mi especial");

        jLabel8.setText("Experiencia");

        experienciaP.setText("mi experiencia");

        imagenPersonaje.setMaximumSize(new java.awt.Dimension(300, 450));
        imagenPersonaje.setMinimumSize(new java.awt.Dimension(300, 450));
        imagenPersonaje.setPreferredSize(new java.awt.Dimension(300, 450));

        volver.setText("Volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                volverMouseReleased(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(imagenPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(menosVida)
                            .addComponent(menosDaño)
                            .addComponent(menosEspecial))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEspecial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(especial))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(daño))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(87, 87, 87)
                                        .addComponent(vida)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(masVida)
                                    .addComponent(masDaño)
                                    .addComponent(masEspecial)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34)
                                .addComponent(puntosNivel)))
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(labelEspecialP))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(experienciaP)
                            .addComponent(nivel)
                            .addComponent(nombreP)
                            .addComponent(vidaP)
                            .addComponent(dañoP)
                            .addComponent(especialP))
                        .addGap(264, 264, 264))))
            .addGroup(layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(volver)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombreP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nivel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(experienciaP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(vidaP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dañoP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEspecialP)
                            .addComponent(especialP))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(puntosNivel))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(vida)
                            .addComponent(masVida)
                            .addComponent(menosVida))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(daño)
                            .addComponent(masDaño)
                            .addComponent(menosDaño))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEspecial)
                            .addComponent(especial)
                            .addComponent(masEspecial)
                            .addComponent(menosEspecial)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(imagenPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masVidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masVidaMouseReleased
        if(masVida.isEnabled()){
            miPersonaje.aumentarBonusVida();
            consultasBD.instancia().modificarMiPersonaje(miPersonaje, registrado);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_masVidaMouseReleased

    private void masDañoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masDañoMouseReleased
        if(masDaño.isEnabled()){
            miPersonaje.aumentarBonusDaño();
            consultasBD.instancia().modificarMiPersonaje(miPersonaje, registrado);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_masDañoMouseReleased

    private void masEspecialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masEspecialMouseReleased
        if(masEspecial.isEnabled()){
            if(miPersonaje instanceof MiTanque){
                MiTanque mt =(MiTanque) miPersonaje;
                mt.aumentarArmadura();
                consultasBD.instancia().modificarMiPersonaje(mt, registrado);
            }
            else if(miPersonaje instanceof MiAsesino){
                MiAsesino ma =(MiAsesino) miPersonaje;
                ma.aumentarEsquivar();
                consultasBD.instancia().modificarMiPersonaje(ma, registrado);
            }
            else if(miPersonaje instanceof MiFighter){
                MiFighter mf =(MiFighter) miPersonaje;
                mf.aumentarCritico();
                consultasBD.instancia().modificarMiPersonaje(mf, registrado);
            }
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_masEspecialMouseReleased

    private void menosVidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosVidaMouseReleased
        if(menosVida.isEnabled()){
            miPersonaje.disminuirBonusVida();
            consultasBD.instancia().modificarMiPersonaje(miPersonaje, registrado);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_menosVidaMouseReleased

    private void menosDañoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosDañoMouseReleased
        if(menosDaño.isEnabled()){
            miPersonaje.disminuirBonusDaño();
            consultasBD.instancia().modificarMiPersonaje(miPersonaje, registrado);
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_menosDañoMouseReleased

    private void menosEspecialMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosEspecialMouseReleased
        if(menosEspecial.isEnabled()){
            if(miPersonaje instanceof MiTanque){
                MiTanque mt =(MiTanque) miPersonaje;
                mt.disminuirArmadura();
                consultasBD.instancia().modificarMiPersonaje(mt, registrado);
            }
            else if(miPersonaje instanceof MiAsesino){
                MiAsesino ma =(MiAsesino) miPersonaje;
                ma.disminuirEsquivar();
                consultasBD.instancia().modificarMiPersonaje(ma, registrado);
            }
            else if(miPersonaje instanceof MiFighter){
                MiFighter mf =(MiFighter) miPersonaje;
                mf.disminuirCritico();
                consultasBD.instancia().modificarMiPersonaje(mf, registrado);
            }
            this.mostrar();
            this.setVisible(true);
        }
    }//GEN-LAST:event_menosEspecialMouseReleased

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    private void volverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseReleased
        this.setVisible(false);
        mp.mostrar();
        mp.setVisible(true);
    }//GEN-LAST:event_volverMouseReleased
    public void mostrar(){
        vida.setText(Float.toString(miPersonaje.getBonusVida()));
        daño.setText(Float.toString(miPersonaje.getBonusDaño()));
        puntosNivel.setText(Integer.toString(miPersonaje.getPuntosNivel()));
        nombreP.setText(miPersonaje.getNombre());
        nivel.setText(Integer.toString(miPersonaje.getNivel()));
        experienciaP.setText(Integer.toString(miPersonaje.getExperiencia()));
        vidaP.setText(Float.toString(miPersonaje.getVidaBase()));
        dañoP.setText(Float.toString(miPersonaje.getDañoBase()));
        Image img=new ImageIcon(this.getClass().getResource("/Imagenes/Personajes/"+this.miPersonaje.getNombre()+".jpg")).getImage();
        imagenPersonaje.setIcon(new ImageIcon(img));
        float aEspecial=0;
        if(miPersonaje instanceof MiTanque){
            MiTanque mt=(MiTanque) miPersonaje;
            labelEspecial.setText("Bonus de armadura");
            especial.setText(Float.toString(mt.getBonusArmadura()));
            aEspecial=mt.getBonusArmadura();
            labelEspecialP.setText("Armadura");
            especialP.setText(Float.toString(mt.getPersonaje().getArmadura()));
        }
        else if(miPersonaje instanceof MiAsesino){
            MiAsesino ma=(MiAsesino) miPersonaje;
            labelEspecial.setText("Bonus de esquivar");
            especial.setText(Float.toString(ma.getBonusEsquivar()));
            aEspecial=ma.getBonusEsquivar();
            labelEspecialP.setText("Esquivar");
            especialP.setText(Float.toString(ma.getPersonaje().getEsquivar()));
        }
        else if(miPersonaje instanceof MiFighter){
            MiFighter mf=(MiFighter) miPersonaje;
            labelEspecial.setText("Bonus de crítico");
            especial.setText(Float.toString(mf.getBonusCritico()));
            aEspecial=mf.getBonusCritico();
            labelEspecialP.setText("Crítico");
            especialP.setText(Float.toString(mf.getPersonaje().getCritico()));
        }
        
        if(miPersonaje.getPuntosNivel()<=0){
            masDaño.setEnabled(false);
            masVida.setEnabled(false);
            masEspecial.setEnabled(false);
        }
        else{
            if(miPersonaje.getBonusVida()>=(10*LIMITE_ATRIBUTO)){//la vida aumenta en 10 cada vez que se sube un punto
                masVida.setEnabled(false);
            } else {
                masVida.setEnabled(true);
            }
            if (miPersonaje.getBonusDaño()>=(5*LIMITE_ATRIBUTO)){//el daño aumenta en 5 cada vez que se sube un punto
                masDaño.setEnabled(false);
            } else {
                masDaño.setEnabled(true);
            }
            if(aEspecial>=LIMITE_ATRIBUTO){//el especial aumenta en 1 cada vez que se sube un punto
                masEspecial.setEnabled(false);
            } else {
                masEspecial.setEnabled(true);
            }            
        }
        
        if(miPersonaje.getBonusVida()<=0){
            menosVida.setEnabled(false);
        } else {
            menosVida.setEnabled(true);
        }
        if(miPersonaje.getBonusDaño()<=0){
            menosDaño.setEnabled(false);
        } else {
            menosDaño.setEnabled(true);
        }
        if(aEspecial<=0){
            menosEspecial.setEnabled(false);
        } else {
            menosEspecial.setEnabled(true);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtributosMiPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtributosMiPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtributosMiPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtributosMiPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AtributosMiPersonaje dialog = new AtributosMiPersonaje(new javax.swing.JFrame(), true,null,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daño;
    private javax.swing.JLabel dañoP;
    private javax.swing.JLabel especial;
    private javax.swing.JLabel especialP;
    private javax.swing.JLabel experienciaP;
    private javax.swing.JLabel imagenPersonaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelEspecial;
    private javax.swing.JLabel labelEspecialP;
    private javax.swing.JButton masDaño;
    private javax.swing.JButton masEspecial;
    private javax.swing.JButton masVida;
    private javax.swing.JButton menosDaño;
    private javax.swing.JButton menosEspecial;
    private javax.swing.JButton menosVida;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel nombreP;
    private javax.swing.JLabel puntosNivel;
    private javax.swing.JLabel vida;
    private javax.swing.JLabel vidaP;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
