/**
 * Interfaz gráfica que muestra los personajes que tiene un usuario y desde la que
 * se accederá a la interfaz para modificar las propiedades del personajes
 */
package InterfazGrafica.registrado;

import MiPersonaje.MiAsesino;
import MiPersonaje.MiFighter;
import MiPersonaje.MiPersonaje;
import MiPersonaje.MiTanque;
import ciclodeinstruccion.Usuarios.Registrado;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class MisPersonajes extends javax.swing.JDialog {

    /**
     * Creates new form MisPersonajes
     */
    private Registrado registrado;
    private InicioRegistrado ir;
    private MiPersonaje mp=null;
    public MisPersonajes(java.awt.Frame parent, boolean modal,Registrado r, InicioRegistrado ir) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();  
        this.setLocationRelativeTo(null);
        this.registrado=r;
        this.ir=ir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atributos = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chuckNorris = new javax.swing.JButton();
        donkeyKong = new javax.swing.JButton();
        gollum = new javax.swing.JButton();
        Lucario = new javax.swing.JButton();
        luigi = new javax.swing.JButton();
        mABaracus = new javax.swing.JButton();
        mario = new javax.swing.JButton();
        samus = new javax.swing.JButton();
        sonic = new javax.swing.JButton();
        info = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nivel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        daño = new javax.swing.JLabel();
        especialL = new javax.swing.JLabel();
        especial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        atributos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/modificar_propiedades.png"))); // NOI18N
        atributos.setBorder(null);
        atributos.setBorderPainted(false);
        atributos.setContentAreaFilled(false);
        atributos.setFocusPainted(false);
        atributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atributosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atributosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atributosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                atributosMouseReleased(evt);
            }
        });
        atributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atributosActionPerformed(evt);
            }
        });
        getContentPane().add(atributos);
        atributos.setBounds(250, 630, 260, 65);

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/volver.png"))); // NOI18N
        volver.setBorder(null);
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setFocusPainted(false);
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                volverMouseReleased(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver);
        volver.setBounds(770, 630, 260, 65);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,200));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Selecciona un personaje");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 10, 340, 50);

        chuckNorris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/Chuck Norris.png"))); // NOI18N
        chuckNorris.setBorder(null);
        chuckNorris.setBorderPainted(false);
        chuckNorris.setContentAreaFilled(false);
        chuckNorris.setFocusPainted(false);
        chuckNorris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuckNorrisActionPerformed(evt);
            }
        });
        jPanel1.add(chuckNorris);
        chuckNorris.setBounds(60, 90, 100, 100);

        donkeyKong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/Donkey Kong.png"))); // NOI18N
        donkeyKong.setBorder(null);
        donkeyKong.setBorderPainted(false);
        donkeyKong.setContentAreaFilled(false);
        donkeyKong.setFocusPainted(false);
        donkeyKong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donkeyKongActionPerformed(evt);
            }
        });
        jPanel1.add(donkeyKong);
        donkeyKong.setBounds(200, 90, 100, 100);

        gollum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/Gollum.png"))); // NOI18N
        gollum.setBorder(null);
        gollum.setBorderPainted(false);
        gollum.setContentAreaFilled(false);
        gollum.setFocusPainted(false);
        gollum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gollumActionPerformed(evt);
            }
        });
        jPanel1.add(gollum);
        gollum.setBounds(340, 90, 100, 100);

        Lucario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/Lucario.png"))); // NOI18N
        Lucario.setBorder(null);
        Lucario.setBorderPainted(false);
        Lucario.setContentAreaFilled(false);
        Lucario.setFocusPainted(false);
        Lucario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LucarioActionPerformed(evt);
            }
        });
        jPanel1.add(Lucario);
        Lucario.setBounds(60, 230, 100, 100);

        luigi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/Luigi.png"))); // NOI18N
        luigi.setBorder(null);
        luigi.setBorderPainted(false);
        luigi.setContentAreaFilled(false);
        luigi.setFocusPainted(false);
        luigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luigiActionPerformed(evt);
            }
        });
        jPanel1.add(luigi);
        luigi.setBounds(200, 230, 100, 100);

        mABaracus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/M. A. Baracus.png"))); // NOI18N
        mABaracus.setBorder(null);
        mABaracus.setBorderPainted(false);
        mABaracus.setContentAreaFilled(false);
        mABaracus.setFocusPainted(false);
        mABaracus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mABaracusActionPerformed(evt);
            }
        });
        jPanel1.add(mABaracus);
        mABaracus.setBounds(340, 230, 100, 100);

        mario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/Mario.png"))); // NOI18N
        mario.setBorder(null);
        mario.setBorderPainted(false);
        mario.setContentAreaFilled(false);
        mario.setFocusPainted(false);
        mario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marioActionPerformed(evt);
            }
        });
        jPanel1.add(mario);
        mario.setBounds(60, 370, 100, 100);

        samus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/Samus.png"))); // NOI18N
        samus.setBorder(null);
        samus.setBorderPainted(false);
        samus.setContentAreaFilled(false);
        samus.setFocusPainted(false);
        samus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samusActionPerformed(evt);
            }
        });
        jPanel1.add(samus);
        samus.setBounds(200, 370, 100, 100);

        sonic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PjCaras/Sonic.png"))); // NOI18N
        sonic.setBorder(null);
        sonic.setBorderPainted(false);
        sonic.setContentAreaFilled(false);
        sonic.setFocusPainted(false);
        sonic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonicActionPerformed(evt);
            }
        });
        jPanel1.add(sonic);
        sonic.setBounds(340, 370, 100, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 60, 500, 530);

        info.setBackground(new java.awt.Color(0, 0, 0,200));
        info.setLayout(null);

        imagen.setMaximumSize(new java.awt.Dimension(150, 225));
        imagen.setMinimumSize(new java.awt.Dimension(150, 225));
        imagen.setPreferredSize(new java.awt.Dimension(150, 225));
        info.add(imagen);
        imagen.setBounds(50, 150, 150, 225);

        nombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 102, 51));
        nombre.setText("Nombre");
        info.add(nombre);
        nombre.setBounds(260, 30, 250, 60);

        tipo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tipo.setForeground(new java.awt.Color(255, 102, 51));
        tipo.setText("Tipo");
        info.add(tipo);
        tipo.setBounds(260, 100, 230, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Nivel");
        info.add(jLabel3);
        jLabel3.setBounds(260, 180, 61, 60);

        nivel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nivel.setForeground(new java.awt.Color(255, 102, 51));
        nivel.setText("miNivel");
        info.add(nivel);
        nivel.setBounds(420, 180, 91, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Vida");
        info.add(jLabel4);
        jLabel4.setBounds(260, 260, 52, 60);

        vida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vida.setForeground(new java.awt.Color(255, 102, 51));
        vida.setText("miVida");
        info.add(vida);
        vida.setBounds(420, 260, 82, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Daño");
        info.add(jLabel5);
        jLabel5.setBounds(260, 350, 62, 60);

        daño.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        daño.setForeground(new java.awt.Color(255, 102, 51));
        daño.setText("miDaño");
        info.add(daño);
        daño.setBounds(420, 350, 92, 60);

        especialL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        especialL.setForeground(new java.awt.Color(255, 102, 51));
        especialL.setText("Especial");
        info.add(especialL);
        especialL.setBounds(260, 440, 150, 60);

        especial.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        especial.setForeground(new java.awt.Color(255, 102, 51));
        especial.setText("miEspecial");
        info.add(especial);
        especial.setBounds(420, 440, 127, 60);

        getContentPane().add(info);
        info.setBounds(660, 60, 560, 530);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_normal.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atributosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atributosMouseReleased
        if(this.mp!=null){
            AtributosMiPersonaje amp= new AtributosMiPersonaje(null, true, mp, registrado,this);
            this.setVisible(false);
            amp.mostrar();
            amp.setVisible(true);
        }
    }//GEN-LAST:event_atributosMouseReleased

    private void volverMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseReleased
        this.setVisible(false);
        ir.setVisible(true);
    }//GEN-LAST:event_volverMouseReleased

    private void atributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atributosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atributosActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    private void volverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMousePressed
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/volver.png")));
    }//GEN-LAST:event_volverMousePressed

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/volver.png")));
    }//GEN-LAST:event_volverMouseExited

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/volver.png")));
    }//GEN-LAST:event_volverMouseEntered

    private void atributosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atributosMousePressed
        atributos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/modificar_propiedades.png")));
    }//GEN-LAST:event_atributosMousePressed

    private void atributosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atributosMouseExited
        atributos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/modificar_propiedades.png")));
    }//GEN-LAST:event_atributosMouseExited

    private void atributosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atributosMouseEntered
        atributos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/modificar_propiedades.png")));
    }//GEN-LAST:event_atributosMouseEntered

    private void chuckNorrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuckNorrisActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("Chuck Norris"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_chuckNorrisActionPerformed

    private void donkeyKongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donkeyKongActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("Donkey Kong"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_donkeyKongActionPerformed

    private void gollumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gollumActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("Gollum"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_gollumActionPerformed

    private void LucarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LucarioActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("Lucario"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_LucarioActionPerformed

    private void luigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luigiActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("Luigi"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_luigiActionPerformed

    private void mABaracusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mABaracusActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("M. A. Baracus"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_mABaracusActionPerformed

    private void marioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marioActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("Mario"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_marioActionPerformed

    private void samusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samusActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("Samus"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_samusActionPerformed

    private void sonicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonicActionPerformed
        this.mp=registrado.getMisPersonajes().get(registrado.buscarMiPersonaje("Sonic"));
        this.mostrarPersonaje(mp);
        this.info.setVisible(true);
    }//GEN-LAST:event_sonicActionPerformed
    /**
     * Método que deshabilita los botones que corresponden con los personajes
     * que el usuario no tiene
     */
    public void mostrar(){
        this.info.setVisible(false);
        if(registrado.buscarMiPersonaje("Chuck Norris")==-1){
            this.chuckNorris.setEnabled(false);
        }
        if(registrado.buscarMiPersonaje("Donkey Kong")==-1){
            this.donkeyKong.setEnabled(false);
        }
        if(registrado.buscarMiPersonaje("Gollum")==-1){
            this.gollum.setEnabled(false);
        }
        if(registrado.buscarMiPersonaje("Lucario")==-1){
            this.Lucario.setEnabled(false);
        }
        if(registrado.buscarMiPersonaje("Luigi")==-1){
            this.luigi.setEnabled(false);
        }
        if(registrado.buscarMiPersonaje("M. A. Baracus")==-1){
            this.mABaracus.setEnabled(false);
        }
        if(registrado.buscarMiPersonaje("Mario")==-1){
            this.mario.setEnabled(false);
        }
        if(registrado.buscarMiPersonaje("Samus")==-1){
            this.samus.setEnabled(false);
        }
        if(registrado.buscarMiPersonaje("Sonic")==-1){
            this.sonic.setEnabled(false);
        }
    }
    /**
     * Método que muestra en el lateral un panel con información sobre el personaje 
     * seleccionado
     * @param mp personaje elegido 
     */
    public void mostrarPersonaje(MiPersonaje mp){
        Image img1=new ImageIcon(this.getClass().getResource("/Imagenes/PjPequeños/"+mp.getNombre()+".png")).getImage();
        this.imagen.setIcon(new ImageIcon(img1));
        this.nombre.setText(mp.getNombre());
        this.tipo.setText(mp.getTipo());
        this.nivel.setText(Integer.toString(mp.getNivel()));
        this.vida.setText(Float.toString(mp.getVidaBase()+mp.getBonusVida()));
        this.daño.setText(Float.toString(mp.getDañoBase()+mp.getBonusDaño()));
        if(mp instanceof MiTanque){
            this.especialL.setText("Armadura");
            MiTanque p=(MiTanque) mp;
            this.especial.setText(Float.toString(p.getPersonaje().getArmadura()+p.getBonusArmadura()));
        }
        else if(mp instanceof MiAsesino){
            this.especialL.setText("Esquivar");
            MiAsesino p=(MiAsesino) mp;
            this.especial.setText(Float.toString(p.getPersonaje().getEsquivar()+p.getBonusEsquivar()));
        }
        else if(mp instanceof MiFighter){
            this.especialL.setText("Critico");
            MiFighter p=(MiFighter) mp;
            this.especial.setText(Float.toString(p.getPersonaje().getCritico()+p.getBonusCritico()));
        }
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisPersonajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MisPersonajes dialog = new MisPersonajes(new javax.swing.JFrame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lucario;
    private javax.swing.JButton atributos;
    private javax.swing.JButton chuckNorris;
    private javax.swing.JLabel daño;
    private javax.swing.JButton donkeyKong;
    private javax.swing.JLabel especial;
    private javax.swing.JLabel especialL;
    private javax.swing.JButton gollum;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton luigi;
    private javax.swing.JButton mABaracus;
    private javax.swing.JButton mario;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton samus;
    private javax.swing.JButton sonic;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel vida;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
