/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica.registrado;

import InterfazGrafica.Inicio;
import ciclodeinstruccion.Partida;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Rubén
 */
public class VerPartida extends javax.swing.JDialog {

    /**
     * Creates new form VerPartida
     */
    private Partida partida;
    private int cont;
    private boolean jugar;
    private InicioRegistrado ir;
    private boolean prueba;
    private Inicio i;
    private boolean repeticion;
    private Estadisticas e;
    
    public VerPartida(java.awt.Frame parent, boolean modal,Partida p,boolean jugar ,InicioRegistrado ir,boolean prueba, Inicio i, boolean repeticion, Estadisticas e) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();  
        this.setLocationRelativeTo(null);
        this.partida=p;
        this.cont=1;
        this.jugar=jugar;
        this.ir=ir;
        this.prueba=prueba;
        this.i=i;
        this.repeticion=repeticion;
        this.e=e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        siguiente = new javax.swing.JButton();
        imagenP1 = new javax.swing.JLabel();
        imagenP2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jugador1 = new javax.swing.JLabel();
        jugador2 = new javax.swing.JLabel();
        vidaj1 = new javax.swing.JLabel();
        vidaj2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0,0));

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(0, 0, 0,200));
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 51, 0));
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 115, 600, 290);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);

        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/siguiente.png"))); // NOI18N
        siguiente.setBorder(null);
        siguiente.setBorderPainted(false);
        siguiente.setContentAreaFilled(false);
        siguiente.setFocusPainted(false);
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siguienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                siguienteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                siguiente(evt);
            }
        });
        getContentPane().add(siguiente);
        siguiente.setBounds(350, 480, 260, 65);

        imagenP1.setMaximumSize(new java.awt.Dimension(300, 450));
        imagenP1.setMinimumSize(new java.awt.Dimension(300, 450));
        imagenP1.setPreferredSize(new java.awt.Dimension(300, 450));
        getContentPane().add(imagenP1);
        imagenP1.setBounds(30, 110, 300, 450);

        imagenP2.setMaximumSize(new java.awt.Dimension(300, 450));
        imagenP2.setMinimumSize(new java.awt.Dimension(300, 450));
        imagenP2.setPreferredSize(new java.awt.Dimension(300, 450));
        getContentPane().add(imagenP2);
        imagenP2.setBounds(950, 110, 300, 450);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/volver.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 480, 260, 65);

        jugador1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jugador1.setForeground(new java.awt.Color(255, 102, 51));
        jugador1.setText("JUGADOR1");
        getContentPane().add(jugador1);
        jugador1.setBounds(30, 60, 270, 60);

        jugador2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jugador2.setForeground(new java.awt.Color(255, 102, 51));
        jugador2.setText("JUGADOR2");
        getContentPane().add(jugador2);
        jugador2.setBounds(950, 60, 270, 60);

        vidaj1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vidaj1.setForeground(new java.awt.Color(255, 0, 51));
        vidaj1.setText("vidaj1");
        getContentPane().add(vidaj1);
        vidaj1.setBounds(80, 600, 100, 50);

        vidaj2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        vidaj2.setForeground(new java.awt.Color(255, 0, 51));
        vidaj2.setText("vidaj2");
        getContentPane().add(vidaj2);
        vidaj2.setBounds(1020, 600, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_normal.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguiente(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguiente
        if(cont<partida.getTexto().size()){
            texto.setText(texto.getText()+"\n"+partida.getTexto().get(cont));
            vidaj1.setText(Float.toString(partida.getVidaJ1().get(cont)));
            vidaj2.setText(Float.toString(partida.getVidaJ2().get(cont)));
            cont++;
        }
        if(cont>=partida.getTexto().size()){
            siguiente.setEnabled(false);
            if(partida.getJugador1().getNombre().equals(partida.getGanador().getNombre())){
                Image img1=new ImageIcon(this.getClass().getResource("/Imagenes/Ganador/"+this.partida.getPersonaje1().getNombre()+".jpg")).getImage();
                imagenP1.setIcon(new ImageIcon(img1));
                Image img2=new ImageIcon(this.getClass().getResource("/Imagenes/Perdedor/"+this.partida.getPersonaje2().getNombre()+".jpg")).getImage();
                imagenP2.setIcon(new ImageIcon(img2));
            }
            else{
                Image img1=new ImageIcon(this.getClass().getResource("/Imagenes/Perdedor/"+this.partida.getPersonaje1().getNombre()+".jpg")).getImage();
                imagenP1.setIcon(new ImageIcon(img1));
                Image img2=new ImageIcon(this.getClass().getResource("/Imagenes/Ganador/"+this.partida.getPersonaje2().getNombre()+".jpg")).getImage();
                imagenP2.setIcon(new ImageIcon(img2));
            }
        }
    }//GEN-LAST:event_siguiente

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        this.setVisible(false);
        if(jugar){
            ir.mostrar();
            ir.setVisible(true);
        }
        else if(prueba){
            i.setVisible(true);
        }
        else if(repeticion){
            e.mostrar2();
            e.mostrar3();
            e.mostrar4();
            e.setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/volver.png")));
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/volver.png")));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/volver.png")));
    }//GEN-LAST:event_jButton1MouseEntered

    private void siguienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMousePressed
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/siguiente.png")));
    }//GEN-LAST:event_siguienteMousePressed

    private void siguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseExited
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/siguiente.png")));
    }//GEN-LAST:event_siguienteMouseExited

    private void siguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseEntered
        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/siguiente.png")));
    }//GEN-LAST:event_siguienteMouseEntered
    public void mostrar(){
        jugador1.setText(partida.getJugador1().getNombre());
        jugador2.setText(partida.getJugador2().getNombre());
        Image img1=new ImageIcon(this.getClass().getResource("/Imagenes/Personajes/"+this.partida.getPersonaje1().getNombre()+".jpg")).getImage();
        imagenP1.setIcon(new ImageIcon(img1));
        Image img2=new ImageIcon(this.getClass().getResource("/Imagenes/Personajes/"+this.partida.getPersonaje2().getNombre()+".jpg")).getImage();
        imagenP2.setIcon(new ImageIcon(img2));
        texto.setText(partida.getTexto().get(0));
        texto.setText(texto.getText()+"\n"+partida.getTexto().get(cont));
        vidaj1.setText(Float.toString(partida.getVidaJ1().get(cont)));
        vidaj2.setText(Float.toString(partida.getVidaJ2().get(cont)));
        cont++;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerPartida dialog = new VerPartida(new javax.swing.JFrame(), true,null,true,null,true,null,true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenP1;
    private javax.swing.JLabel imagenP2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador2;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel vidaj1;
    private javax.swing.JLabel vidaj2;
    // End of variables declaration//GEN-END:variables
}
