/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica.administrador;

import InterfazGrafica.Inicio;
import InterfazGrafica.administrador.EstadisticasAvanzadas;
import InterfazGrafica.administrador.VerHistorialAdministrador;
import InterfazGrafica.administrador.VerUsuarios;
import ciclodeinstruccion.Usuarios.Administrador;

/**
 *
 * @author Rubén
 */
public class InicioAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form InicioAdministrador
     */
    private Administrador admin;
    private Inicio i;
    public InicioAdministrador(Administrador a) {
        this.setUndecorated(true);
        initComponents();  
        this.setLocationRelativeTo(null);
        this.admin=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historialPartidas = new javax.swing.JButton();
        gestionarUsuarios = new javax.swing.JButton();
        estadisticas = new javax.swing.JButton();
        gestionarPersonajes = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        historialPartidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/historial_de_partidas.png"))); // NOI18N
        historialPartidas.setBorderPainted(false);
        historialPartidas.setContentAreaFilled(false);
        historialPartidas.setFocusPainted(false);
        historialPartidas.setMaximumSize(new java.awt.Dimension(260, 65));
        historialPartidas.setMinimumSize(new java.awt.Dimension(260, 65));
        historialPartidas.setPreferredSize(new java.awt.Dimension(260, 65));
        historialPartidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historialPartidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historialPartidasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                historialPartidasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                historialPartidasMouseReleased(evt);
            }
        });
        historialPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialPartidasActionPerformed(evt);
            }
        });
        getContentPane().add(historialPartidas);
        historialPartidas.setBounds(530, 110, 260, 65);

        gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/gestionar_usuarios.png"))); // NOI18N
        gestionarUsuarios.setBorderPainted(false);
        gestionarUsuarios.setContentAreaFilled(false);
        gestionarUsuarios.setFocusPainted(false);
        gestionarUsuarios.setMaximumSize(new java.awt.Dimension(260, 65));
        gestionarUsuarios.setMinimumSize(new java.awt.Dimension(260, 65));
        gestionarUsuarios.setPreferredSize(new java.awt.Dimension(260, 65));
        gestionarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gestionarUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gestionarUsuariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gestionarUsuariosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gestionarUsuariosMouseReleased(evt);
            }
        });
        gestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(gestionarUsuarios);
        gestionarUsuarios.setBounds(530, 200, 260, 65);

        estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/estadisticas.png"))); // NOI18N
        estadisticas.setBorderPainted(false);
        estadisticas.setContentAreaFilled(false);
        estadisticas.setFocusPainted(false);
        estadisticas.setMaximumSize(new java.awt.Dimension(260, 65));
        estadisticas.setMinimumSize(new java.awt.Dimension(260, 65));
        estadisticas.setPreferredSize(new java.awt.Dimension(260, 65));
        estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estadisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estadisticasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estadisticasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                estadisticasMouseReleased(evt);
            }
        });
        estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasActionPerformed(evt);
            }
        });
        getContentPane().add(estadisticas);
        estadisticas.setBounds(530, 290, 260, 65);

        gestionarPersonajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/gestionar_personajes.png"))); // NOI18N
        gestionarPersonajes.setBorderPainted(false);
        gestionarPersonajes.setContentAreaFilled(false);
        gestionarPersonajes.setFocusPainted(false);
        gestionarPersonajes.setMaximumSize(new java.awt.Dimension(260, 65));
        gestionarPersonajes.setMinimumSize(new java.awt.Dimension(260, 65));
        gestionarPersonajes.setPreferredSize(new java.awt.Dimension(260, 65));
        gestionarPersonajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gestionarPersonajesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gestionarPersonajesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gestionarPersonajesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gestionarPersonajesMouseReleased(evt);
            }
        });
        gestionarPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarPersonajesActionPerformed(evt);
            }
        });
        getContentPane().add(gestionarPersonajes);
        gestionarPersonajes.setBounds(530, 380, 260, 65);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/salir.png"))); // NOI18N
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setFocusPainted(false);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salirMouseReleased(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(530, 470, 260, 65);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_normal.jpg"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarUsuariosActionPerformed

    private void historialPartidasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialPartidasMouseReleased
        VerHistorialAdministrador va = new VerHistorialAdministrador(this, true, admin,this);
        va.mostrar();
        this.setVisible(false);
        va.setVisible(true);
    }//GEN-LAST:event_historialPartidasMouseReleased

    private void historialPartidasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialPartidasMousePressed
        historialPartidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/historial_de_partidas.png")));
    }//GEN-LAST:event_historialPartidasMousePressed

    private void historialPartidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialPartidasMouseExited
         historialPartidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/historial_de_partidas.png")));
    }//GEN-LAST:event_historialPartidasMouseExited

    private void historialPartidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialPartidasMouseEntered
        historialPartidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/historial_de_partidas.png")));
    }//GEN-LAST:event_historialPartidasMouseEntered

    private void historialPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialPartidasActionPerformed
        
    }//GEN-LAST:event_historialPartidasActionPerformed

    private void gestionarUsuariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarUsuariosMouseReleased
        VerUsuarios vu= new VerUsuarios(this, true, admin,this);
        vu.mostrar();
        this.setVisible(false);
        vu.setVisible(true);
    }//GEN-LAST:event_gestionarUsuariosMouseReleased

    private void estadisticasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticasMouseReleased
        EstadisticasAvanzadas ea= new EstadisticasAvanzadas(this, true, admin,this);
        ea.mostrar();
        this.setVisible(false);
        ea.setVisible(true);
    }//GEN-LAST:event_estadisticasMouseReleased

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadisticasActionPerformed

    private void gestionarPersonajesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarPersonajesMouseReleased
        VerPersonajes vp = new VerPersonajes(this, true, admin,this);
        vp.mostrar();
        this.setVisible(false);
        vp.setVisible(true);
    }//GEN-LAST:event_gestionarPersonajesMouseReleased

    private void gestionarPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarPersonajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionarPersonajesActionPerformed

    private void gestionarUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarUsuariosMousePressed
        gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/gestionar_usuarios.png")));
    }//GEN-LAST:event_gestionarUsuariosMousePressed

    private void gestionarUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarUsuariosMouseExited
        gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/gestionar_usuarios.png")));
    }//GEN-LAST:event_gestionarUsuariosMouseExited

    private void gestionarUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarUsuariosMouseEntered
        gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/gestionar_usuarios.png")));
    }//GEN-LAST:event_gestionarUsuariosMouseEntered

    private void estadisticasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticasMousePressed
        estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/estadisticas.png")));
    }//GEN-LAST:event_estadisticasMousePressed

    private void estadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticasMouseExited
        estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/estadisticas.png")));
    }//GEN-LAST:event_estadisticasMouseExited

    private void estadisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticasMouseEntered
        estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/estadisticas.png")));
    }//GEN-LAST:event_estadisticasMouseEntered

    private void gestionarPersonajesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarPersonajesMousePressed
        gestionarPersonajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/gestionar_personajes.png")));
    }//GEN-LAST:event_gestionarPersonajesMousePressed

    private void gestionarPersonajesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarPersonajesMouseExited
        gestionarPersonajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/gestionar_personajes.png")));
    }//GEN-LAST:event_gestionarPersonajesMouseExited

    private void gestionarPersonajesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarPersonajesMouseEntered
        gestionarPersonajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/gestionar_personajes.png")));
    }//GEN-LAST:event_gestionarPersonajesMouseEntered

    private void salirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseReleased
        this.setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_salirMouseReleased

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Pressed/salir.png")));
    }//GEN-LAST:event_salirMousePressed

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Normal/salir.png")));
    }//GEN-LAST:event_salirMouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
       salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones/Hover/salir.png")));
    }//GEN-LAST:event_salirMouseEntered

    public void setI(Inicio i) {
        this.i = i;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAdministrador(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estadisticas;
    private javax.swing.JButton gestionarPersonajes;
    private javax.swing.JButton gestionarUsuarios;
    private javax.swing.JButton historialPartidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
