/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import ciclodeinstruccion.Usuarios.Registrado;
import javax.swing.JOptionPane;

/**
 *
 * @author Rubén
 */
public class InicioRegistrado extends javax.swing.JFrame {

    /**
     * Creates new form InicioRegistrado
     */
    Registrado resgistrado;
    public InicioRegistrado(Registrado r) {
        initComponents();
        this.resgistrado=r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearPartida = new javax.swing.JButton();
        unirsePartida = new javax.swing.JButton();
        historial = new javax.swing.JButton();
        comprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearPartida.setText("Crear Partida");
        crearPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crearPartida(evt);
            }
        });

        unirsePartida.setText("Unirse a partida");
        unirsePartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                unirse(evt);
            }
        });

        historial.setText("Ver historial de partidas");
        historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                verHistorial(evt);
            }
        });

        comprar.setText("Comprar personaje");
        comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                abrirTienda(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comprar)
                    .addComponent(historial)
                    .addComponent(unirsePartida)
                    .addComponent(crearPartida))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(crearPartida)
                .addGap(38, 38, 38)
                .addComponent(unirsePartida)
                .addGap(38, 38, 38)
                .addComponent(historial)
                .addGap(31, 31, 31)
                .addComponent(comprar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearPartida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearPartida
        CrearPartida cp=new CrearPartida(this, true, resgistrado);
        cp.mostrar();
        cp.setVisible(true);
    }//GEN-LAST:event_crearPartida

    private void unirse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unirse
        UnirsePartida up= new UnirsePartida(this, true, resgistrado);
        up.mostrar();
        up.setVisible(true);
    }//GEN-LAST:event_unirse

    private void verHistorial(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verHistorial
        VerHistorial vh=new VerHistorial(this, true, resgistrado);
        vh.mostrar();
        vh.setVisible(true);
    }//GEN-LAST:event_verHistorial

    private void abrirTienda(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirTienda
        Tienda t=new Tienda(this, true, resgistrado);
        t.mostrar();
        t.setVisible(true);
    }//GEN-LAST:event_abrirTienda
    public void mostrar(){
        if(this.resgistrado.getPartidasJugadas()>=Registrado.getLIMITE_PARTIDAS()){
            crearPartida.setEnabled(false);
            unirsePartida.setEnabled(false);
            JOptionPane.showMessageDialog(rootPane, "Has alcanzado el número de partidas máximas permitidas. Vuelve mañana para seguir jugando", "Limite alcanzado", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioRegistrado(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprar;
    private javax.swing.JButton crearPartida;
    private javax.swing.JButton historial;
    private javax.swing.JButton unirsePartida;
    // End of variables declaration//GEN-END:variables
}
